<?xml version="1.0" encoding="utf-8"?><Database Name="ECommerce" Class="CommerceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ECommerce;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ECommerceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BrandMaster" Member="BrandMasters">
    <Type Name="BrandMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryMaster" Member="CategoryMasters">
    <Type Name="CategoryMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ColorMaster" Member="ColorMasters">
    <Type Name="ColorMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NewArrivals" Member="NewArrivals">
    <Type Name="NewArrival">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PriceMaster" Member="PriceMasters">
    <Type Name="PriceMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FromPrice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ToPrice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductMaster" Member="ProductMasters">
    <Type Name="ProductMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SizeMaster" Member="SizeMasters">
    <Type Name="SizeMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductContainer" Member="ProductContainers">
    <Type Name="ProductContainer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BrandId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ColorId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SubCategoryId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Discounted" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiscountedPrice" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SizeId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiscountedPercent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubCategoryMaster" Member="SubCategoryMasters">
    <Type Name="SubCategoryMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CatogoryContainer" Member="CatogoryContainers">
    <Type Name="CatogoryContainer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CatogoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderLine" Member="OrderLines">
    <Type Name="OrderLine">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Units" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BrandId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AdditionalPhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AlternatEmail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderMaster" Member="OrderMasters">
    <Type Name="OrderMaster">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderId" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="total" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>